import localFont from "next/font/local";
import "./globals.css";

const thebrightpause = localFont({
  src: "./fonts/Oxygen.ttf",
  variable: "--font-the-bright-pause",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${thebrightpause.variable}`}>{children}</body>
    </html>
  );
}
